### ISSUE TITLE
Ticket protection

### ISSUE THREAD

**Issue by iRubens** [dmarlow/AspNetTicketBridge#2]
This library works very well for "parsing" existing tokens. What about issuing new tokens? Any clue to obtain the "Protect" method of the [MachineKey](https://github.com/dmarlow/AspNetTicketBridge/blob/master/src/MachineKey.cs) class?

It might be useful to completely replace an existing OWIN OAuth 2.0 server.

**Comment by dmarlow** [comment]
That's an interesting idea. My use case didn't have a need for it, which is why I never pursued it. It would certainly be feasible to add this in. I'm not sure when that would be. If you would like to take a stab and issue a PR, I'd be glad to review.
