### ISSUE TITLE
Apply strong name signature to packaged assembly (NuGet)

### ISSUE THREAD

**Issue by kharrak** [dmarlow/AspNetTicketBridge#8]
Packaged assembly is not strongly named and this is a issue for most projects which have this requirement and include checks in their CI.

Can there be a separate version of this NuGet e.g. AspNetTicketBridge.Strong?

Benefits and references here: https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named

**Comment by hiezust** [comment]
+1

**Comment by caappa** [comment]
+1

**Comment by OpariucAriana** [comment]
+1

**Comment by dmarlow** [comment]
You got it. (may take a bit for it to get indexed correctly in NuGet though)

https://www.nuget.org/packages/AspNetTicketBridge.Strong/

Cheers!
