### ISSUE TITLE
Issue with BuffersAreEqual

### ISSUE THREAD

**Issue by mrc57crm** [dmarlow/AspNetTicketBridge#9]
I am using this library to decrypt bearer tokens with decryption algorithm AES and validation algorithm SHA1. I am always getting a failure (false return) from the BuffersAreEqual method in MachineKey.cs. The buffer counts are the same but the check inside the loop is not matching up. If I simply change the code so that this method always returns true everything seems to work fine and my token is successfully unprotected. I have not been able to determine the reason behind this validation. Why would this validation be failing always and is it important?

**Comment by dmarlow** [comment]
Can you provide an example piece of code that is reproducible?

A good way to test things out is to generate some values for the encryption/decryption key and validation key from here: https://www.allkeysgenerator.com/Random/ASP-Net-MachineKey-Generator.aspx

Then, perform a simple test to validate your scenario. Here's an example:

```csharp
var validationKey = "2027A0E9B28FF27E04106C6FD14CBAA5F51337199B479619AB959B8D004D98BBFEC4DD99DE7071314CC2FB7FDA4DDE606606AF8876BC561D794E690FEDD5799D";
var decryptionKey = "FF43E6DDC129430D8FE74EED59E7F0AF743E04F864DAB2B5";
var plainText = new byte[] { 1, 0, 1 };
var encrypted = AspNetTicketBridge.MachineKeyTicketProtector.Protect(plainText, decryptionKey, validationKey, "AES", "SHA1",
    "User.MachineKey.Protect",
    "Microsoft.Owin.Security.OAuth", "Access_Token", "v1");

var decrypted = AspNetTicketBridge.MachineKeyTicketUnprotector.Unprotect(encrypted, decryptionKey, validationKey, "AES", "SHA1",
    "User.MachineKey.Protect",
    "Microsoft.Owin.Security.OAuth", "Access_Token", "v1");

CollectionAssert.AreEqual(plainText, decrypted);
```

**Comment by mrc57crm** [comment]
Why does this return null for decrypted (plain text comes from an expired token generated by a .Net Framework OAuth token server I am working with)?

      var validationKey = "2027A0E9B28FF27E04106C6FD14CBAA5F51337199B479619AB959B8D004D98BBFEC4DD99DE7071314CC2FB7FDA4DDE606606AF8876BC561D794E690FEDD5799D";
      var decryptionKey = "FF43E6DDC129430D8FE74EED59E7F0AF743E04F864DAB2B5";
      var plainText = WebEncoders.Base64UrlDecode("ivUAz_oTVP-C_SB7M4yJDOYQCJy_3MMI76asGTEQRvs_TBzGylidW2yVgi2mLAUBWjFl9rQqQMyI-9Po0Mcf-XpRXENRN-aJPxoJ494eGjUtUDTV3Xlbqc62AxJL96aWTbx37m4h4S2bg9ac4podREy_Bo_Fng5BXu0F1mltjuohPr0g7FyTavlCf5pDn9tiYrd_e5Kh5URZG7HTDe4aCnvo2A_pjG7aOqndS7wlJc1guOWh3PsER5FqxzFC71eh_YXigQhqfe_BRGOwXFHkAiIdeVs");

      var decrypted = AspNetTicketBridge.MachineKeyTicketUnprotector.Unprotect(plainText, decryptionKey, validationKey, "AES", "SHA1",
          "User.MachineKey.Protect",
          "Microsoft.Owin.Security.OAuth", "Access_Token", "v1");

**Comment by dmarlow** [comment]
Are you sure that data was encrypted using those same parameters (decryptionKey, validationKey, "AES", "SHA1", "User.MachineKey.Protect", "Microsoft.Owin.Security.OAuth", "Access_Token", "v1")?

What if you were to get the clear text, then attempt to encrypt/decrypt to verify end-to-end?

**Comment by mrc57crm** [comment]
I can't tell how it was encrypted. It is an OAuth implementation that does it, but it is all black box in how it works and I can't tell. It doesn't really matter anymore. It does not appear this library will be useful, even though it seemed to be just the thing we needed initially. Going to rewrite our entire implementation with identityserver.io.

Thanks. You can just go ahead and close this issue.
